version: '2'


services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - code-network
    web:
        image: nginx:latest
        ports:
            - "8097:80"
        volumes:
            - ./code:/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: ./docker/php
        volumes:
            - ./code:/code
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        networks:
            - code-network
# Names our volume
volumes:
  my-db:

networks:
    code-network:
        driver: bridge
